input {
  gelf {
    port => 12201
  }
}

filter {
  mutate {
    add_field => {
      "environment" => "${APP_ENV:dev}"
      "project" => "maka"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "maka-logs-%{+YYYY.MM.dd}"
  }
}
